Rename master branch to main 🧙
tektoncd/cli pull request #1316
Opened 2021-03-09 10:00 UTC by vdemeester

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Changes

This updates few reference of `master` to `main` as the default branch
is going to be `main` starting in the next few days.

/hold
/kind cleanup
To be merged once I renamed the branch to `main`.

/cc @tektoncd/cli-collaborators @tektoncd/cli-maintainers 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
NONE
```

2021-03-09 10:39 UTC, vinamra28 requested changes

2021-03-09 10:39 UTC, vinamra28 commented on RELEASE_PROCESS.md
> +  * [test-runner image](https://github.com/tektoncd/plumbing/blob/cli/tekton/images/test-runner/Dockerfile)
```suggestion
  * [test-runner image](https://github.com/tektoncd/plumbing/blob/main/tekton/images/test-runner/Dockerfile)
```

2021-03-09 10:39 UTC, vinamra28 commented on RELEASE_PROCESS.md
> +  * [tkn image](https://github.com/tektoncd/plumbing/blob/cli/tekton/images/tkn/Dockerfile)
```suggestion
  * [tkn image](https://github.com/tektoncd/plumbing/blob/main/tekton/images/tkn/Dockerfile)
```

2021-03-09 10:40 UTC, vdemeester commented on RELEASE_PROCESS.md
> +  * [test-runner image](https://github.com/tektoncd/plumbing/blob/cli/tekton/images/test-runner/Dockerfile)
oh lol 😹

2021-03-09 10:54 UTC, vdemeester commented
/hold cancel

2021-03-09 15:36 UTC, vdemeester commented
/retest

2021-03-09 15:48 UTC, vdemeester commented
/retest

2021-03-09 15:51 UTC, chmouel commented
let there be the dragons

/lgtm

2021-03-09 15:55 UTC, pradeepitm12 approved these changes

2021-03-09 16:03 UTC, vdemeester commented
hum 🤔

2021-03-09 16:08 UTC, vdemeester commented
Retrying to see if those are flake or legit…
/retest

2021-03-09 16:52 UTC, vdemeester commented
```
tektoncd           3m26s       Warning   FailedCreate                   replicaset/el-github-listener-interceptor-64786d4d49                 Error creating: pods "el-github-listener-interceptor-64786d4d49-" is forbidden: error looking up service account tektoncd/tekton-triggers-github-sa: serviceaccount "tekton-triggers-github-sa" not found
```

Is this a race ? or do we miss something ? 🤔

2021-03-09 17:10 UTC, vinamra28 commented
this is what I am trying to see by doing a retest. I just saw that there was one PR related to eventlistener failure

2021-03-09 17:16 UTC, barthy1 commented
based on my tests with `master`, the error was different - 
```
k8s.io/client-go@v0.19.7/tools/cache/reflector.go:156: Failed to watch *v1alpha1.TriggerTemplate: failed to list *v1alpha1.TriggerTemplate: triggertemplates.triggers.tekton.dev is forbidden: User "system:serviceaccount:testcli-67zcj:tekton-triggers-github-sa" cannot list resource "triggertemplates" in API group "triggers.tekton.dev" in the namespace "testcli-67zcj
```

Yesterday the error `looking up service account tektoncd/tekton-triggers-github-sa: serviceaccount "tekton-triggers-github-sa" not found` didn't exist.

2021-03-09 17:19 UTC, vinamra28 commented
also I just did try out the e2e tests locally on my machine for EventListener and they are passing

2021-03-09 17:20 UTC, barthy1 commented
looks like problem with cluster setup? I can see in the error logs of the tests
```
default            105s        Normal    VolumeDelete                   persistentvolume/pvc-def086e6-a100-47c9-bcb0-5ab6e84767c4            googleapi: Error 400: The disk resource 'projects/tekton-prow-11/zones/us-central1-a/disks/gke-tcli-e2e-cls136933-pvc-def086e6-a100-47c9-bcb0-5ab6e84767c4' is already being used by 'projects/tekton-prow-11/zones/us-central1-a/instances/gke-tcli-e2e-cls13693307-default-pool-bc7a78fa-40qh', resourceInUseByAnotherResource
... skipping 115 lines ...
kube-system        6m45s       Warning   FailedCreate                   replicaset/kube-dns-57fcf698d8                                       Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
... skipping 11 lines ...
kube-system        6m45s       Warning   FailedCreate                   replicaset/kube-dns-autoscaler-7f89fb6b79                            Error creating: pods "kube-dns-autoscaler-7f89fb6b79-" is forbidden: error looking up service account kube-system/kube-dns-autoscaler: serviceaccount "kube-dns-autoscaler" not found
... skipping 47 lines ...
kube-system        6m45s       Warning   FailedCreate                   replicaset/metrics-server-v0.3.6-8497fd5d6d                          Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
... skipping 51 lines ...
kube-system        6m44s       Warning   FailedCreate                   replicaset/stackdriver-metadata-agent-cluster-level-569b7b5fb6       Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
... skipping 24 lines ...

```

2021-03-09 18:12 UTC, vinamra28 commented
/retest

2021-03-09 18:23 UTC, barthy1 commented
@vdemeester are you sure you want to delete these resources https://github.com/tektoncd/cli/pull/1316/files#diff-1cbb8009d3d7b4d91bd3f67ca822853185dfe921d7752f44a4408551207bab29L84 ? it looks like reason of the test error you have

2021-03-09 18:27 UTC, barthy1 commented
oops, sorry, now I see that it's just some kind of reformatting. Bit still looks related to the error...

2021-03-10 11:03 UTC, vdemeester commented
/retest

2021-03-10 11:15 UTC, vdemeester commented
Hum…

```
cat: '"/tmp/tmp.CuCk2OKapG/changed_files"': No such file or directory
==========================================='========================================
==== NO CHANGED FILES REPORTED, ASSUMING IT'S AN ERROR AND RUNNING TESTS ANYWAY ====
==========================================='========================================
```

This doesn't seem right, I need to check if there is a problem here.

2021-03-10 14:55 UTC, chmouel reviewed
/lgtm

Looking Good! 🤙🏽

2021-03-10 14:55 UTC, chmouel commented on test/e2e/clustertask/start_test.go
> +	t.Skip("TEMPORARY DISABLING THIS, SEE https://github.com/tektoncd/cli/issues/1319.")
is it temporary? :trollface:

2021-03-10 14:55 UTC, merged