Make chains namespace configurable
tektoncd/cli pull request #1522
Opened 2022-03-08 22:06 UTC by piyush-garg

This makes chains namespace configurable with new flag
chains-namespace where you can specify in which namespace
the chains is configured, by default it is tekton-chains

Do refactoring in chains cmd code

Update docs

Bump chains and hub deps

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Run the code checkers with `make check`
- [ ] Regenerate the manpages, docs and go formatting with `make generated`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```release-note
Make chains namespace configurable
```

2022-03-08 22:06 UTC, piyush-garg commented
/hold

2022-03-09 07:16 UTC, concaf requested changes

2022-03-09 07:16 UTC, concaf commented on docs/cmd/tkn_chain_signature.md
> +Print a Tekton chains' signature for a specific taskrun
```suggestion
Print Tekton Chains' signature for a specific taskrun
```

2022-03-09 07:16 UTC, concaf commented on docs/cmd/tkn_chain_signature.md
> +Print a Tekton chains' signature for a specific taskrun
```suggestion
Print a Tekton Chains' signature for a specific taskrun
```

2022-03-09 07:16 UTC, concaf commented on pkg/cmd/chain/payload.go
> +		Short: "Print a Tekton chains' payload for a specific taskrun",
```suggestion
		Short: "Print Tekton Chains' payload for a specific taskrun",
```

2022-03-09 07:16 UTC, concaf commented on pkg/version/version.go
> +	chainsInfo                     string = "chain-info"
keep this as it is?

2022-03-09 07:24 UTC, piyush-garg commented on pkg/version/version.go
> +	chainsInfo                     string = "chain-info"
fixed

2022-03-09 07:24 UTC, piyush-garg commented on pkg/cmd/chain/payload.go
> +		Short: "Print a Tekton chains' payload for a specific taskrun",
fixed

2022-03-09 07:24 UTC, piyush-garg commented on docs/cmd/tkn_chain_signature.md
> +Print a Tekton chains' signature for a specific taskrun
fixed

2022-03-09 07:24 UTC, piyush-garg commented on docs/cmd/tkn_chain_signature.md
> +Print a Tekton chains' signature for a specific taskrun
fixed

2022-03-09 08:09 UTC, vdemeester approved these changes

2022-03-09 08:53 UTC, piyush-garg commented
/hold cancel

2022-03-09 09:20 UTC, concaf commented
/lgtm

2022-03-09 09:28 UTC, pradeepitm12 approved these changes
/lgtm

2022-03-09 09:29 UTC, merged