Reset TKN_PLUGINS_DIR env during tests
tektoncd/cli pull request #1600
Opened 2022-06-11 09:12 UTC by vinamra28

# Changes

While running tests on local machine, a few tests related to plugins
were failing as a plugin was already present in the local machine. This
case can arise for other developers as well.

This patch sets the value of TKN_PLUGINS_DIR to a random value before
running the tests and restore the original value once the tests are
done.

Signed-off-by: vinamra28 <jvinamra776@gmail.com>
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Run the code checkers with `make check`
- [X] Regenerate the manpages, docs and go formatting with `make generated`
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes
```release-note
NONE
```

2022-06-13 06:41 UTC, piyush-garg commented
/lgtm

2022-06-13 08:03 UTC, chmouel requested changes

2022-06-13 08:03 UTC, chmouel commented on pkg/cmd/root_test.go
> +	os.Setenv("TKN_PLUGINS_DIR", "/non/existing/path")
this would be buggy for other tests, if you don't use a defer env.Patch to cleanup the setting

2022-06-19 15:18 UTC, vinamra28 commented
resolved in #1608. Thanks @piyush-garg 👼 
/close

2022-06-19 15:18 UTC, closed without merging